### ISSUE TITLE
Remove Chef

### ISSUE THREAD

**Issue by CMYanko** [sonatype/docker-nexus-iq-server#39]
Chef was implemented to help deal with installing the OracleJDK and some system items in a cross platform way. Now that we're on OpenJDK and we've shown we can build these without Chef (required in disconnected envionments) do we really need to keep it?

**Comment by hboutemy** [comment]
it looks it has been done in #48

**Comment by bentmann** [comment]
As mentioned above, this was resolved by https://github.com/sonatype/docker-nexus-iq-server/pull/48
