### ISSUE TITLE
nexus user uid conflict with polkitd

### ISSUE THREAD

**Issue by chrismulderza** [sonatype/docker-nexus-iq-server#43]
The chef recipe used to build the docker image does not seem to explicitly define the UID, like the recipe for Nexus repository. Looks like the UID for the nexus user is randomly selected. Current images create the nexus user with UID/GID 998/996. This UID/GID is assigned to polkitd on later versions of Centos. This is an issue when passing a local directory to the container to mount for the data directories.

**Comment by namloc2001** [comment]
Yes, I'd like to understand why the UID is not explicitly defined? When using this container on K8s/OpenShift we ideally need to know this as (especially for OpenShift, where arbitrary IDs are assigned by default).

We've had to set fsGroup: 200 and use the anyuid SCC to ensure the application successfully starts up, but this involved a lot of a digging around to find the answer.

The Chef cookbook merely does:
```
user 'nexus' do
  comment 'Nexus IQ user'
  system true
  shell '/bin/false'
  home node['nexus_iq_server']['install_dir']
  action :create
end
```
(From: chef-nexus-iq-server.tar.gz/chef-nexus-iq-server.tar/cookbooks/nexus_iq_server/recipes/download.rb)

and then this used on a directory that we receive java errors on if we don't use fsGroup:200
```
directory node['nexus_iq_server']['config']['sonatypeWork'] do
  owner 'nexus'
  group 'nexus'
  mode '0755'
  action :create
  recursive true
end
```
(From: chef-nexus-iq-server.tar.gz/chef-nexus-iq-server.tar/cookbooks/nexus_iq_server/recipes/configure.rb)

**Comment by namloc2001** [comment]
What I don't understand is why nexus is given the following UID and GUID:
```
id
uid=998(nexus) gid=996(nexus) groups=996(nexus),200
```
And then I need to give it `200`? Where is the 200 set?

**Comment by bentmann** [comment]
As of https://github.com/sonatype/docker-nexus-iq-server/pull/54, the uid/gid are explicitly specified as different values, resolving this particular issue.
